### ISSUE TITLE
starting docker image only displays help page for useradd command

### ISSUE THREAD

**Issue by gregbert42** [jensdufour/PUB-AirPrint#4]
here is the docker-compose (i didnt change much vs. the example)

```
version: "3"
services:
  airprint:
    image: firilith/airprint:latest
    container_name: airprint
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
#      - CUPSADMIN= #optional
#      - CUPSPASSWORD= #optional
    volumes:
      - /home/remote_fs_user/conf/airprint/services:/services
      - /home/remote_fs_user/conf/airprint/config:/config
      - /var/run/dbus:/var/run/dbus
#    restart: unless-stopped

```

here are the logs:

```
+ grep -ci /etc/shadow
+ [ 0 -eq 0 ]
+ useradd -r -G lpadmin -M
Usage: useradd [options] LOGIN
       useradd -D
       useradd -D [options]

Options:
  -b, --base-dir BASE_DIR       base directory for the home directory of the
                                new account
  -c, --comment COMMENT         GECOS field of the new account
  -d, --home-dir HOME_DIR       home directory of the new account
  -D, --defaults                print or change default useradd configuration
  -e, --expiredate EXPIRE_DATE  expiration date of the new account
  -f, --inactive INACTIVE       password inactivity period of the new account
  -g, --gid GROUP               name or ID of the primary group of the new
                                account
  -G, --groups GROUPS           list of supplementary groups of the new
                                account
  -h, --help                    display this help message and exit
  -k, --skel SKEL_DIR           use this alternative skeleton directory
  -K, --key KEY=VALUE           override /etc/login.defs defaults
  -l, --no-log-init             do not add the user to the lastlog and
                                faillog databases
  -m, --create-home             create the user's home directory
  -M, --no-create-home          do not create the user's home directory
  -N, --no-user-group           do not create a group with the same name as
                                the user
  -o, --non-unique              allow to create users with duplicate
                                (non-unique) UID
  -p, --password PASSWORD       encrypted password of the new account
  -r, --system                  create a system account
  -R, --root CHROOT_DIR         directory to chroot into
  -s, --shell SHELL             login shell of the new account
  -u, --uid UID                 user ID of the new account
  -U, --user-group              create a group with the same name as the user
  -Z, --selinux-user SEUSER     use a specific SEUSER for the SELinux user mapping
      --extrausers              Use the extra users database

```

(and then it exits)

Docker version 20.10.7, build f0df35096d
linux  5.10.21-1-lts  x86_64 GNU/Linux
